on: [push]

name: AzureARMDeploy

jobs:

    deploy: 
      runs-on: ubuntu-latest
      steps:

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Checkout Source Code
        uses: actions/checkout@v2 
      
      - name: Deploy Arm Template
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create \
            --resource-group crc-test-group \
            --template-file armtemplates/webappDeploy.json \
            --parameters armtemplates/parameters.json
            
